[package]
name = "tsukemen"
version = "0.1.0"
authors = ["toku-sa-n <tokusan441@gmail.com>"]
edition = "2018"

[lib]
name = "tsukemen"
crate-type = ["staticlib"]
test = false
bench = false

[dependencies]
syscalls = { path = "../syscalls" }
